A, B, C = map(float, input().split())
TRIANGULO = float((A * C) / 2)
CIRCULO = float(3.14159 * (C ** 2))
TRAPEZIO = float(((A + B) * C) / 2)
QUADRADO = float(B ** 2)
RETANGULO = float(A * B)
print("TRIANGULO: {:.3f}".format(TRIANGULO))
print("CIRCULO: {:.3f}".format(CIRCULO))
print("TRAPEZIO: {:.3f}".format(TRAPEZIO))
print("QUADRADO: {:.3f}".format(QUADRADO))
print("RETANGULO: {:.3f}".format(RETANGULO))
